# SITE CONFIGURATION
baseurl: ""
url: "https://frsanchez.github.io/"

# THEME-SPECIFIC CONFIGURATION
title: Sanchez Parra Labs Blog                                   # site's title
description: A blog about coding, photography and weekenders      # used by search engines
avatar: assets/img/favicon/favicon-96x96.png                         # Empty for no avatar in navbar
favicon: assets/img/favicon/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Sanchez Parra Labs  # Change Blog header text
header_feature_image: assets/img/20170707_050418.jpg
footer_text: >
  2020 © <a href="https://github.com/FrSanchez">Francisco Sanchez</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
katex: true                                             # Enable if using math markup
google_analytics: UA-156236534-1                        # Tracking ID, e.g. "UA-000000-01"
disqus_shortname: frsanchez-github-io-2                 # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 8
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js",
          "oldposts", "js-src/*", "queuedPages/*", .travis.yml]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
# remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
